# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ata50.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(899, 751)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/ATA50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 133, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(292, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("img/ATA50.png"))
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(291, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 1, 2, 1, 1)
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(28)
        font.setItalic(True)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 3, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 192, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 4, 1, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_24 = QtWidgets.QLabel(self.tab_2)
        self.label_24.setObjectName("label_24")
        self.gridLayout_4.addWidget(self.label_24, 0, 0, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_4.addWidget(self.lineEdit_5, 0, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(438, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem4, 0, 2, 1, 1)
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_2)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_55 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_55.setObjectName("gridLayout_55")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_9.addWidget(self.label_14, 0, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_4.setEnabled(False)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_9.addWidget(self.lineEdit_4, 0, 1, 1, 1)
        self.gridLayout_55.addLayout(self.gridLayout_9, 0, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 1, 1, 1)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.dateTimeEdit.setFont(font)
        self.dateTimeEdit.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2017, 12, 31), QtCore.QTime(0, 0, 0)))
        self.dateTimeEdit.setMaximumTime(QtCore.QTime(12, 59, 59))
        self.dateTimeEdit.setMinimumTime(QtCore.QTime(0, 0, 0))
        self.dateTimeEdit.setTimeSpec(QtCore.Qt.LocalTime)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.gridLayout_3.addWidget(self.dateTimeEdit, 1, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_2.setMinimumSize(QtCore.QSize(75, 25))
        self.pushButton_2.setMaximumSize(QtCore.QSize(25, 75))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_3.addWidget(self.pushButton_2, 1, 1, 1, 1)
        self.gridLayout_55.addLayout(self.gridLayout_3, 1, 0, 1, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_6.addWidget(self.label_4, 0, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_6.addWidget(self.comboBox, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_6.addWidget(self.label_5, 1, 0, 1, 1)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.doubleSpinBox.setFont(font)
        self.doubleSpinBox.setMaximum(20000.0)
        self.doubleSpinBox.setSingleStep(0.1)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout_6.addWidget(self.doubleSpinBox, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_6.addWidget(self.label_6, 2, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout_6.addWidget(self.comboBox_2, 2, 1, 1, 1)
        self.gridLayout_55.addLayout(self.gridLayout_6, 2, 0, 1, 1)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_10.addWidget(self.label_9, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_10.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_3.setMinimumSize(QtCore.QSize(75, 25))
        self.pushButton_3.setMaximumSize(QtCore.QSize(25, 75))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_10.addWidget(self.pushButton_3, 0, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_10.addWidget(self.label_10, 1, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_10.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.gridLayout_10.addWidget(self.label_12, 1, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_10.addWidget(self.label_11, 2, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_10.addWidget(self.lineEdit_3, 2, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.gridLayout_10.addWidget(self.label_13, 2, 2, 1, 1)
        self.gridLayout_55.addLayout(self.gridLayout_10, 3, 0, 1, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_20 = QtWidgets.QLabel(self.groupBox_2)
        self.label_20.setObjectName("label_20")
        self.gridLayout_7.addWidget(self.label_20, 0, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBox_2)
        self.label_21.setObjectName("label_21")
        self.gridLayout_7.addWidget(self.label_21, 0, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.groupBox_2)
        self.label_22.setObjectName("label_22")
        self.gridLayout_7.addWidget(self.label_22, 0, 2, 1, 1)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.gridLayout_7.addWidget(self.doubleSpinBox_2, 1, 0, 1, 1)
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.gridLayout_7.addWidget(self.doubleSpinBox_3, 1, 1, 1, 1)
        self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.gridLayout_7.addWidget(self.doubleSpinBox_4, 1, 2, 1, 1)
        self.gridLayout_55.addLayout(self.gridLayout_7, 4, 0, 1, 1)
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_68 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_68.setFont(font)
        self.label_68.setObjectName("label_68")
        self.gridLayout_14.addWidget(self.label_68, 0, 0, 1, 1)
        self.comboBox_19 = QtWidgets.QComboBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_19.setFont(font)
        self.comboBox_19.setObjectName("comboBox_19")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.gridLayout_14.addWidget(self.comboBox_19, 0, 1, 1, 1)
        self.gridLayout_55.addLayout(self.gridLayout_14, 5, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_55.addWidget(self.label_8, 6, 0, 1, 1)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout_55.addWidget(self.plainTextEdit, 7, 0, 1, 4)
        spacerItem5 = QtWidgets.QSpacerItem(317, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_55.addItem(spacerItem5, 8, 0, 1, 2)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_4.setMinimumSize(QtCore.QSize(125, 25))
        self.pushButton_4.setMaximumSize(QtCore.QSize(125, 75))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_55.addWidget(self.pushButton_4, 8, 2, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton.setMinimumSize(QtCore.QSize(75, 25))
        self.pushButton.setMaximumSize(QtCore.QSize(25, 75))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_55.addWidget(self.pushButton, 8, 3, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(235, 24, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_55.addItem(spacerItem6, 5, 1, 1, 3)
        spacerItem7 = QtWidgets.QSpacerItem(235, 49, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_55.addItem(spacerItem7, 4, 1, 1, 3)
        spacerItem8 = QtWidgets.QSpacerItem(235, 86, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_55.addItem(spacerItem8, 3, 1, 1, 3)
        spacerItem9 = QtWidgets.QSpacerItem(235, 86, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_55.addItem(spacerItem9, 2, 1, 1, 3)
        spacerItem10 = QtWidgets.QSpacerItem(235, 50, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_55.addItem(spacerItem10, 1, 1, 1, 3)
        spacerItem11 = QtWidgets.QSpacerItem(235, 24, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_55.addItem(spacerItem11, 0, 1, 1, 3)
        self.gridLayout_8.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox.setMinimumSize(QtCore.QSize(275, 600))
        self.groupBox.setMaximumSize(QtCore.QSize(275, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.listWidget = QtWidgets.QListWidget(self.groupBox)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout_5.addWidget(self.listWidget, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox, 0, 1, 1, 1)
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_35 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_35.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_35.setObjectName("gridLayout_35")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.tab_6)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.gridLayout_35.addWidget(self.plainTextEdit_2, 4, 0, 1, 3)
        self.label_19 = QtWidgets.QLabel(self.tab_6)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridLayout_35.addWidget(self.label_19, 3, 0, 1, 3)
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_38 = QtWidgets.QLabel(self.tab_6)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.gridLayout_15.addWidget(self.label_38, 0, 0, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.tab_6)
        self.label_32.setText("")
        self.label_32.setObjectName("label_32")
        self.gridLayout_15.addWidget(self.label_32, 0, 1, 1, 1)
        self.dateTimeEdit_2 = QtWidgets.QDateTimeEdit(self.tab_6)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.dateTimeEdit_2.setFont(font)
        self.dateTimeEdit_2.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2017, 12, 31), QtCore.QTime(0, 0, 0)))
        self.dateTimeEdit_2.setMaximumTime(QtCore.QTime(12, 59, 59))
        self.dateTimeEdit_2.setMinimumTime(QtCore.QTime(0, 0, 0))
        self.dateTimeEdit_2.setTimeSpec(QtCore.Qt.LocalTime)
        self.dateTimeEdit_2.setObjectName("dateTimeEdit_2")
        self.gridLayout_15.addWidget(self.dateTimeEdit_2, 1, 0, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_7.setMinimumSize(QtCore.QSize(75, 25))
        self.pushButton_7.setMaximumSize(QtCore.QSize(25, 75))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_15.addWidget(self.pushButton_7, 1, 1, 1, 1)
        self.gridLayout_35.addLayout(self.gridLayout_15, 0, 0, 1, 3)
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_15 = QtWidgets.QLabel(self.tab_6)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_11.addWidget(self.label_15, 0, 0, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.tab_6)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setObjectName("comboBox_3")
        self.gridLayout_11.addWidget(self.comboBox_3, 0, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.tab_6)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout_11.addWidget(self.label_16, 1, 0, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(self.tab_6)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_4.setFont(font)
        self.comboBox_4.setObjectName("comboBox_4")
        self.gridLayout_11.addWidget(self.comboBox_4, 1, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.tab_6)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout_11.addWidget(self.label_17, 2, 0, 1, 1)
        self.comboBox_5 = QtWidgets.QComboBox(self.tab_6)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_5.setFont(font)
        self.comboBox_5.setObjectName("comboBox_5")
        self.gridLayout_11.addWidget(self.comboBox_5, 2, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.tab_6)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout_11.addWidget(self.label_18, 3, 0, 1, 1)
        self.comboBox_6 = QtWidgets.QComboBox(self.tab_6)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_6.setFont(font)
        self.comboBox_6.setObjectName("comboBox_6")
        self.gridLayout_11.addWidget(self.comboBox_6, 3, 1, 1, 1)
        self.gridLayout_35.addLayout(self.gridLayout_11, 1, 0, 1, 3)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_3.setMinimumSize(QtCore.QSize(275, 600))
        self.groupBox_3.setMaximumSize(QtCore.QSize(275, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.listWidget_2 = QtWidgets.QListWidget(self.groupBox_3)
        self.listWidget_2.setObjectName("listWidget_2")
        self.gridLayout_12.addWidget(self.listWidget_2, 0, 0, 1, 1)
        self.gridLayout_35.addWidget(self.groupBox_3, 0, 3, 6, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_6)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.groupBox_4)
        self.plainTextEdit_3.setEnabled(False)
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.gridLayout_13.addWidget(self.plainTextEdit_3, 0, 0, 1, 1)
        self.gridLayout_35.addWidget(self.groupBox_4, 2, 0, 1, 3)
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_5.setMinimumSize(QtCore.QSize(75, 25))
        self.pushButton_5.setMaximumSize(QtCore.QSize(25, 75))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_35.addWidget(self.pushButton_5, 5, 2, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_6.setMinimumSize(QtCore.QSize(125, 25))
        self.pushButton_6.setMaximumSize(QtCore.QSize(125, 75))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_35.addWidget(self.pushButton_6, 5, 1, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(337, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_35.addItem(spacerItem12, 5, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.tabWidget_2.addTab(self.tab_7, "")
        self.gridLayout_4.addWidget(self.tabWidget_2, 1, 0, 1, 3)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_26.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.tabWidget_8 = QtWidgets.QTabWidget(self.tab_3)
        self.tabWidget_8.setObjectName("tabWidget_8")
        self.tab_28 = QtWidgets.QWidget()
        self.tab_28.setObjectName("tab_28")
        self.gridLayout_34 = QtWidgets.QGridLayout(self.tab_28)
        self.gridLayout_34.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_34.setObjectName("gridLayout_34")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_28)
        self.groupBox_5.setMinimumSize(QtCore.QSize(275, 600))
        self.groupBox_5.setMaximumSize(QtCore.QSize(275, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_27 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.label_28 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.gridLayout_27.addWidget(self.label_28, 0, 0, 1, 1)
        self.listWidget_3 = QtWidgets.QListWidget(self.groupBox_5)
        self.listWidget_3.setObjectName("listWidget_3")
        self.gridLayout_27.addWidget(self.listWidget_3, 1, 0, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.gridLayout_27.addWidget(self.label_29, 2, 0, 1, 1)
        self.listWidget_4 = QtWidgets.QListWidget(self.groupBox_5)
        self.listWidget_4.setObjectName("listWidget_4")
        self.gridLayout_27.addWidget(self.listWidget_4, 3, 0, 1, 1)
        self.gridLayout_34.addWidget(self.groupBox_5, 0, 0, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_28)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_32 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_32.setObjectName("gridLayout_32")
        self.gridLayout_29 = QtWidgets.QGridLayout()
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.label_30 = QtWidgets.QLabel(self.groupBox_6)
        self.label_30.setObjectName("label_30")
        self.gridLayout_29.addWidget(self.label_30, 0, 0, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_6.setEnabled(False)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_29.addWidget(self.lineEdit_6, 0, 1, 1, 1)
        self.gridLayout_32.addLayout(self.gridLayout_29, 0, 0, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(272, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_32.addItem(spacerItem13, 0, 1, 1, 1)
        self.gridLayout_30 = QtWidgets.QGridLayout()
        self.gridLayout_30.setObjectName("gridLayout_30")
        self.label_31 = QtWidgets.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.gridLayout_30.addWidget(self.label_31, 0, 0, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_10.setEnabled(False)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout_30.addWidget(self.lineEdit_10, 1, 0, 1, 1)
        self.gridLayout_32.addLayout(self.gridLayout_30, 1, 0, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(272, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_32.addItem(spacerItem14, 1, 1, 1, 1)
        self.gridLayout_31 = QtWidgets.QGridLayout()
        self.gridLayout_31.setObjectName("gridLayout_31")
        self.label_33 = QtWidgets.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.gridLayout_31.addWidget(self.label_33, 0, 0, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.gridLayout_31.addWidget(self.label_34, 1, 0, 1, 1)
        self.doubleSpinBox_5 = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.doubleSpinBox_5.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.doubleSpinBox_5.setFont(font)
        self.doubleSpinBox_5.setMaximum(20000.0)
        self.doubleSpinBox_5.setSingleStep(0.1)
        self.doubleSpinBox_5.setObjectName("doubleSpinBox_5")
        self.gridLayout_31.addWidget(self.doubleSpinBox_5, 1, 1, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.gridLayout_31.addWidget(self.label_35, 2, 0, 1, 1)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_11.setEnabled(False)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout_31.addWidget(self.lineEdit_11, 0, 1, 1, 1)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_12.setEnabled(False)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout_31.addWidget(self.lineEdit_12, 2, 1, 1, 1)
        self.gridLayout_32.addLayout(self.gridLayout_31, 2, 0, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(272, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_32.addItem(spacerItem15, 2, 1, 1, 1)
        self.gridLayout_28 = QtWidgets.QGridLayout()
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.label_36 = QtWidgets.QLabel(self.groupBox_6)
        self.label_36.setObjectName("label_36")
        self.gridLayout_28.addWidget(self.label_36, 0, 0, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_7.setEnabled(False)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout_28.addWidget(self.lineEdit_7, 0, 1, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.groupBox_6)
        self.label_37.setObjectName("label_37")
        self.gridLayout_28.addWidget(self.label_37, 1, 0, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_8.setEnabled(False)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout_28.addWidget(self.lineEdit_8, 1, 1, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.groupBox_6)
        self.label_39.setObjectName("label_39")
        self.gridLayout_28.addWidget(self.label_39, 2, 0, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_9.setEnabled(False)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout_28.addWidget(self.lineEdit_9, 2, 1, 1, 1)
        self.gridLayout_32.addLayout(self.gridLayout_28, 3, 0, 1, 1)
        self.gridLayout_33 = QtWidgets.QGridLayout()
        self.gridLayout_33.setObjectName("gridLayout_33")
        self.label_41 = QtWidgets.QLabel(self.groupBox_6)
        self.label_41.setObjectName("label_41")
        self.gridLayout_33.addWidget(self.label_41, 0, 0, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.groupBox_6)
        self.label_42.setObjectName("label_42")
        self.gridLayout_33.addWidget(self.label_42, 0, 1, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.groupBox_6)
        self.label_43.setObjectName("label_43")
        self.gridLayout_33.addWidget(self.label_43, 0, 2, 1, 1)
        self.doubleSpinBox_6 = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.doubleSpinBox_6.setEnabled(False)
        self.doubleSpinBox_6.setObjectName("doubleSpinBox_6")
        self.gridLayout_33.addWidget(self.doubleSpinBox_6, 1, 0, 1, 1)
        self.doubleSpinBox_7 = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.doubleSpinBox_7.setEnabled(False)
        self.doubleSpinBox_7.setObjectName("doubleSpinBox_7")
        self.gridLayout_33.addWidget(self.doubleSpinBox_7, 1, 1, 1, 1)
        self.doubleSpinBox_8 = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.doubleSpinBox_8.setEnabled(False)
        self.doubleSpinBox_8.setObjectName("doubleSpinBox_8")
        self.gridLayout_33.addWidget(self.doubleSpinBox_8, 1, 2, 1, 1)
        self.gridLayout_32.addLayout(self.gridLayout_33, 4, 0, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.groupBox_6)
        self.label_44.setObjectName("label_44")
        self.gridLayout_32.addWidget(self.label_44, 5, 0, 1, 1)
        self.plainTextEdit_8 = QtWidgets.QPlainTextEdit(self.groupBox_6)
        self.plainTextEdit_8.setEnabled(False)
        self.plainTextEdit_8.setObjectName("plainTextEdit_8")
        self.gridLayout_32.addWidget(self.plainTextEdit_8, 6, 0, 1, 3)
        spacerItem16 = QtWidgets.QSpacerItem(278, 86, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_32.addItem(spacerItem16, 3, 1, 1, 2)
        spacerItem17 = QtWidgets.QSpacerItem(278, 49, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_32.addItem(spacerItem17, 4, 1, 1, 2)
        self.gridLayout_34.addWidget(self.groupBox_6, 0, 1, 1, 1)
        self.tabWidget_8.addTab(self.tab_28, "")
        self.tab_29 = QtWidgets.QWidget()
        self.tab_29.setObjectName("tab_29")
        self.gridLayout_36 = QtWidgets.QGridLayout(self.tab_29)
        self.gridLayout_36.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_36.setObjectName("gridLayout_36")
        self.tabWidget_9 = QtWidgets.QTabWidget(self.tab_29)
        self.tabWidget_9.setObjectName("tabWidget_9")
        self.tab_31 = QtWidgets.QWidget()
        self.tab_31.setObjectName("tab_31")
        self.gridLayout_41 = QtWidgets.QGridLayout(self.tab_31)
        self.gridLayout_41.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_41.setObjectName("gridLayout_41")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_31)
        self.groupBox_7.setMinimumSize(QtCore.QSize(275, 550))
        self.groupBox_7.setMaximumSize(QtCore.QSize(275, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_37 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_37.setObjectName("gridLayout_37")
        self.listWidget_5 = QtWidgets.QListWidget(self.groupBox_7)
        self.listWidget_5.setObjectName("listWidget_5")
        self.gridLayout_37.addWidget(self.listWidget_5, 0, 0, 1, 1)
        self.gridLayout_41.addWidget(self.groupBox_7, 0, 0, 5, 1)
        self.gridLayout_40 = QtWidgets.QGridLayout()
        self.gridLayout_40.setObjectName("gridLayout_40")
        self.label_49 = QtWidgets.QLabel(self.tab_31)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_49.setFont(font)
        self.label_49.setObjectName("label_49")
        self.gridLayout_40.addWidget(self.label_49, 0, 0, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.tab_31)
        self.label_50.setText("")
        self.label_50.setObjectName("label_50")
        self.gridLayout_40.addWidget(self.label_50, 0, 1, 1, 1)
        self.dateTimeEdit_3 = QtWidgets.QDateTimeEdit(self.tab_31)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.dateTimeEdit_3.setFont(font)
        self.dateTimeEdit_3.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2017, 12, 31), QtCore.QTime(0, 0, 0)))
        self.dateTimeEdit_3.setMaximumTime(QtCore.QTime(12, 59, 59))
        self.dateTimeEdit_3.setMinimumTime(QtCore.QTime(0, 0, 0))
        self.dateTimeEdit_3.setTimeSpec(QtCore.Qt.LocalTime)
        self.dateTimeEdit_3.setObjectName("dateTimeEdit_3")
        self.gridLayout_40.addWidget(self.dateTimeEdit_3, 1, 0, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_31)
        self.pushButton_8.setMinimumSize(QtCore.QSize(75, 25))
        self.pushButton_8.setMaximumSize(QtCore.QSize(25, 75))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_40.addWidget(self.pushButton_8, 1, 1, 1, 1)
        self.gridLayout_41.addLayout(self.gridLayout_40, 0, 1, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(267, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_41.addItem(spacerItem18, 0, 2, 1, 1)
        self.gridLayout_38 = QtWidgets.QGridLayout()
        self.gridLayout_38.setObjectName("gridLayout_38")
        self.label_40 = QtWidgets.QLabel(self.tab_31)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.gridLayout_38.addWidget(self.label_40, 0, 0, 1, 1)
        self.comboBox_7 = QtWidgets.QComboBox(self.tab_31)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_7.setFont(font)
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.gridLayout_38.addWidget(self.comboBox_7, 0, 1, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.tab_31)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")
        self.gridLayout_38.addWidget(self.label_45, 1, 0, 1, 1)
        self.comboBox_8 = QtWidgets.QComboBox(self.tab_31)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_8.setFont(font)
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.gridLayout_38.addWidget(self.comboBox_8, 1, 1, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.tab_31)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_46.setFont(font)
        self.label_46.setObjectName("label_46")
        self.gridLayout_38.addWidget(self.label_46, 2, 0, 1, 1)
        self.comboBox_9 = QtWidgets.QComboBox(self.tab_31)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_9.setFont(font)
        self.comboBox_9.setObjectName("comboBox_9")
        self.gridLayout_38.addWidget(self.comboBox_9, 2, 1, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.tab_31)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_47.setFont(font)
        self.label_47.setObjectName("label_47")
        self.gridLayout_38.addWidget(self.label_47, 3, 0, 1, 1)
        self.comboBox_10 = QtWidgets.QComboBox(self.tab_31)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_10.setFont(font)
        self.comboBox_10.setObjectName("comboBox_10")
        self.gridLayout_38.addWidget(self.comboBox_10, 3, 1, 1, 1)
        self.gridLayout_41.addLayout(self.gridLayout_38, 1, 1, 1, 1)
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_31)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_39 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_39.setObjectName("gridLayout_39")
        self.plainTextEdit_10 = QtWidgets.QPlainTextEdit(self.groupBox_8)
        self.plainTextEdit_10.setEnabled(False)
        self.plainTextEdit_10.setObjectName("plainTextEdit_10")
        self.gridLayout_39.addWidget(self.plainTextEdit_10, 0, 0, 1, 1)
        self.gridLayout_41.addWidget(self.groupBox_8, 1, 2, 3, 1)
        spacerItem19 = QtWidgets.QSpacerItem(20, 170, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_41.addItem(spacerItem19, 2, 1, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.tab_31)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_48.setFont(font)
        self.label_48.setObjectName("label_48")
        self.gridLayout_41.addWidget(self.label_48, 3, 1, 1, 1)
        self.plainTextEdit_9 = QtWidgets.QPlainTextEdit(self.tab_31)
        self.plainTextEdit_9.setObjectName("plainTextEdit_9")
        self.gridLayout_41.addWidget(self.plainTextEdit_9, 4, 1, 1, 2)
        self.tabWidget_9.addTab(self.tab_31, "")
        self.tab_32 = QtWidgets.QWidget()
        self.tab_32.setObjectName("tab_32")
        self.gridLayout_46 = QtWidgets.QGridLayout(self.tab_32)
        self.gridLayout_46.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_46.setObjectName("gridLayout_46")
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_32)
        self.groupBox_10.setMinimumSize(QtCore.QSize(275, 550))
        self.groupBox_10.setMaximumSize(QtCore.QSize(275, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_44 = QtWidgets.QGridLayout(self.groupBox_10)
        self.gridLayout_44.setObjectName("gridLayout_44")
        self.listWidget_6 = QtWidgets.QListWidget(self.groupBox_10)
        self.listWidget_6.setObjectName("listWidget_6")
        self.gridLayout_44.addWidget(self.listWidget_6, 0, 0, 1, 1)
        self.gridLayout_46.addWidget(self.groupBox_10, 0, 0, 5, 1)
        self.gridLayout_45 = QtWidgets.QGridLayout()
        self.gridLayout_45.setObjectName("gridLayout_45")
        self.label_56 = QtWidgets.QLabel(self.tab_32)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_56.setFont(font)
        self.label_56.setObjectName("label_56")
        self.gridLayout_45.addWidget(self.label_56, 0, 0, 1, 1)
        self.label_57 = QtWidgets.QLabel(self.tab_32)
        self.label_57.setText("")
        self.label_57.setObjectName("label_57")
        self.gridLayout_45.addWidget(self.label_57, 0, 1, 1, 1)
        self.dateTimeEdit_4 = QtWidgets.QDateTimeEdit(self.tab_32)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.dateTimeEdit_4.setFont(font)
        self.dateTimeEdit_4.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2017, 12, 31), QtCore.QTime(0, 0, 0)))
        self.dateTimeEdit_4.setMaximumTime(QtCore.QTime(12, 59, 59))
        self.dateTimeEdit_4.setMinimumTime(QtCore.QTime(0, 0, 0))
        self.dateTimeEdit_4.setTimeSpec(QtCore.Qt.LocalTime)
        self.dateTimeEdit_4.setObjectName("dateTimeEdit_4")
        self.gridLayout_45.addWidget(self.dateTimeEdit_4, 1, 0, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_32)
        self.pushButton_9.setMinimumSize(QtCore.QSize(75, 25))
        self.pushButton_9.setMaximumSize(QtCore.QSize(25, 75))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_45.addWidget(self.pushButton_9, 1, 1, 1, 1)
        self.gridLayout_46.addLayout(self.gridLayout_45, 0, 1, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(267, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_46.addItem(spacerItem20, 0, 2, 1, 1)
        self.gridLayout_42 = QtWidgets.QGridLayout()
        self.gridLayout_42.setObjectName("gridLayout_42")
        self.label_51 = QtWidgets.QLabel(self.tab_32)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_51.setFont(font)
        self.label_51.setObjectName("label_51")
        self.gridLayout_42.addWidget(self.label_51, 0, 0, 1, 1)
        self.comboBox_11 = QtWidgets.QComboBox(self.tab_32)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_11.setFont(font)
        self.comboBox_11.setObjectName("comboBox_11")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.gridLayout_42.addWidget(self.comboBox_11, 0, 1, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.tab_32)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_52.setFont(font)
        self.label_52.setObjectName("label_52")
        self.gridLayout_42.addWidget(self.label_52, 1, 0, 1, 1)
        self.comboBox_12 = QtWidgets.QComboBox(self.tab_32)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_12.setFont(font)
        self.comboBox_12.setObjectName("comboBox_12")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.gridLayout_42.addWidget(self.comboBox_12, 1, 1, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.tab_32)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_53.setFont(font)
        self.label_53.setObjectName("label_53")
        self.gridLayout_42.addWidget(self.label_53, 2, 0, 1, 1)
        self.comboBox_13 = QtWidgets.QComboBox(self.tab_32)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_13.setFont(font)
        self.comboBox_13.setObjectName("comboBox_13")
        self.gridLayout_42.addWidget(self.comboBox_13, 2, 1, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.tab_32)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_54.setFont(font)
        self.label_54.setObjectName("label_54")
        self.gridLayout_42.addWidget(self.label_54, 3, 0, 1, 1)
        self.comboBox_14 = QtWidgets.QComboBox(self.tab_32)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_14.setFont(font)
        self.comboBox_14.setObjectName("comboBox_14")
        self.gridLayout_42.addWidget(self.comboBox_14, 3, 1, 1, 1)
        self.gridLayout_46.addLayout(self.gridLayout_42, 1, 1, 1, 1)
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab_32)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_43 = QtWidgets.QGridLayout(self.groupBox_9)
        self.gridLayout_43.setObjectName("gridLayout_43")
        self.plainTextEdit_12 = QtWidgets.QPlainTextEdit(self.groupBox_9)
        self.plainTextEdit_12.setEnabled(False)
        self.plainTextEdit_12.setObjectName("plainTextEdit_12")
        self.gridLayout_43.addWidget(self.plainTextEdit_12, 0, 0, 1, 1)
        self.gridLayout_46.addWidget(self.groupBox_9, 1, 2, 3, 1)
        spacerItem21 = QtWidgets.QSpacerItem(20, 170, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_46.addItem(spacerItem21, 2, 1, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.tab_32)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_55.setFont(font)
        self.label_55.setObjectName("label_55")
        self.gridLayout_46.addWidget(self.label_55, 3, 1, 1, 1)
        self.plainTextEdit_11 = QtWidgets.QPlainTextEdit(self.tab_32)
        self.plainTextEdit_11.setObjectName("plainTextEdit_11")
        self.gridLayout_46.addWidget(self.plainTextEdit_11, 4, 1, 1, 2)
        self.tabWidget_9.addTab(self.tab_32, "")
        self.tab_33 = QtWidgets.QWidget()
        self.tab_33.setObjectName("tab_33")
        self.gridLayout_51 = QtWidgets.QGridLayout(self.tab_33)
        self.gridLayout_51.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_51.setObjectName("gridLayout_51")
        self.groupBox_12 = QtWidgets.QGroupBox(self.tab_33)
        self.groupBox_12.setMinimumSize(QtCore.QSize(275, 550))
        self.groupBox_12.setMaximumSize(QtCore.QSize(275, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_12.setFont(font)
        self.groupBox_12.setObjectName("groupBox_12")
        self.gridLayout_49 = QtWidgets.QGridLayout(self.groupBox_12)
        self.gridLayout_49.setObjectName("gridLayout_49")
        self.listWidget_7 = QtWidgets.QListWidget(self.groupBox_12)
        self.listWidget_7.setObjectName("listWidget_7")
        self.gridLayout_49.addWidget(self.listWidget_7, 0, 0, 1, 1)
        self.gridLayout_51.addWidget(self.groupBox_12, 0, 0, 5, 1)
        self.gridLayout_50 = QtWidgets.QGridLayout()
        self.gridLayout_50.setObjectName("gridLayout_50")
        self.label_63 = QtWidgets.QLabel(self.tab_33)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_63.setFont(font)
        self.label_63.setObjectName("label_63")
        self.gridLayout_50.addWidget(self.label_63, 0, 0, 1, 1)
        self.label_64 = QtWidgets.QLabel(self.tab_33)
        self.label_64.setText("")
        self.label_64.setObjectName("label_64")
        self.gridLayout_50.addWidget(self.label_64, 0, 1, 1, 1)
        self.dateTimeEdit_5 = QtWidgets.QDateTimeEdit(self.tab_33)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.dateTimeEdit_5.setFont(font)
        self.dateTimeEdit_5.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2017, 12, 31), QtCore.QTime(0, 0, 0)))
        self.dateTimeEdit_5.setMaximumTime(QtCore.QTime(12, 59, 59))
        self.dateTimeEdit_5.setMinimumTime(QtCore.QTime(0, 0, 0))
        self.dateTimeEdit_5.setTimeSpec(QtCore.Qt.LocalTime)
        self.dateTimeEdit_5.setObjectName("dateTimeEdit_5")
        self.gridLayout_50.addWidget(self.dateTimeEdit_5, 1, 0, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_33)
        self.pushButton_10.setMinimumSize(QtCore.QSize(75, 25))
        self.pushButton_10.setMaximumSize(QtCore.QSize(25, 75))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_50.addWidget(self.pushButton_10, 1, 1, 1, 1)
        self.gridLayout_51.addLayout(self.gridLayout_50, 0, 1, 1, 1)
        spacerItem22 = QtWidgets.QSpacerItem(267, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_51.addItem(spacerItem22, 0, 2, 1, 1)
        self.gridLayout_47 = QtWidgets.QGridLayout()
        self.gridLayout_47.setObjectName("gridLayout_47")
        self.label_58 = QtWidgets.QLabel(self.tab_33)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_58.setFont(font)
        self.label_58.setObjectName("label_58")
        self.gridLayout_47.addWidget(self.label_58, 0, 0, 1, 1)
        self.comboBox_15 = QtWidgets.QComboBox(self.tab_33)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_15.setFont(font)
        self.comboBox_15.setObjectName("comboBox_15")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.gridLayout_47.addWidget(self.comboBox_15, 0, 1, 1, 1)
        self.label_59 = QtWidgets.QLabel(self.tab_33)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_59.setFont(font)
        self.label_59.setObjectName("label_59")
        self.gridLayout_47.addWidget(self.label_59, 1, 0, 1, 1)
        self.comboBox_16 = QtWidgets.QComboBox(self.tab_33)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_16.setFont(font)
        self.comboBox_16.setObjectName("comboBox_16")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.gridLayout_47.addWidget(self.comboBox_16, 1, 1, 1, 1)
        self.label_60 = QtWidgets.QLabel(self.tab_33)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_60.setFont(font)
        self.label_60.setObjectName("label_60")
        self.gridLayout_47.addWidget(self.label_60, 2, 0, 1, 1)
        self.comboBox_17 = QtWidgets.QComboBox(self.tab_33)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_17.setFont(font)
        self.comboBox_17.setObjectName("comboBox_17")
        self.gridLayout_47.addWidget(self.comboBox_17, 2, 1, 1, 1)
        self.label_61 = QtWidgets.QLabel(self.tab_33)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_61.setFont(font)
        self.label_61.setObjectName("label_61")
        self.gridLayout_47.addWidget(self.label_61, 3, 0, 1, 1)
        self.comboBox_18 = QtWidgets.QComboBox(self.tab_33)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_18.setFont(font)
        self.comboBox_18.setObjectName("comboBox_18")
        self.gridLayout_47.addWidget(self.comboBox_18, 3, 1, 1, 1)
        self.gridLayout_51.addLayout(self.gridLayout_47, 1, 1, 1, 1)
        self.groupBox_11 = QtWidgets.QGroupBox(self.tab_33)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_11.setFont(font)
        self.groupBox_11.setObjectName("groupBox_11")
        self.gridLayout_48 = QtWidgets.QGridLayout(self.groupBox_11)
        self.gridLayout_48.setObjectName("gridLayout_48")
        self.plainTextEdit_14 = QtWidgets.QPlainTextEdit(self.groupBox_11)
        self.plainTextEdit_14.setEnabled(False)
        self.plainTextEdit_14.setObjectName("plainTextEdit_14")
        self.gridLayout_48.addWidget(self.plainTextEdit_14, 0, 0, 1, 1)
        self.gridLayout_51.addWidget(self.groupBox_11, 1, 2, 3, 1)
        spacerItem23 = QtWidgets.QSpacerItem(20, 170, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_51.addItem(spacerItem23, 2, 1, 1, 1)
        self.label_62 = QtWidgets.QLabel(self.tab_33)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_62.setFont(font)
        self.label_62.setObjectName("label_62")
        self.gridLayout_51.addWidget(self.label_62, 3, 1, 1, 1)
        self.plainTextEdit_13 = QtWidgets.QPlainTextEdit(self.tab_33)
        self.plainTextEdit_13.setObjectName("plainTextEdit_13")
        self.gridLayout_51.addWidget(self.plainTextEdit_13, 4, 1, 1, 2)
        self.tabWidget_9.addTab(self.tab_33, "")
        self.gridLayout_36.addWidget(self.tabWidget_9, 0, 0, 1, 1)
        self.tabWidget_8.addTab(self.tab_29, "")
        self.tab_30 = QtWidgets.QWidget()
        self.tab_30.setObjectName("tab_30")
        self.tabWidget_8.addTab(self.tab_30, "")
        self.gridLayout_26.addWidget(self.tabWidget_8, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_16.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.tab_4)
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.tab_8)
        self.gridLayout_17.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.plainTextEdit_4 = QtWidgets.QPlainTextEdit(self.tab_8)
        self.plainTextEdit_4.setObjectName("plainTextEdit_4")
        self.gridLayout_17.addWidget(self.plainTextEdit_4, 0, 0, 1, 1)
        self.tabWidget_3.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.tab_9)
        self.gridLayout_18.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.tabWidget_4 = QtWidgets.QTabWidget(self.tab_9)
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.tab_12)
        self.gridLayout_22.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_22.setObjectName("gridLayout_22")
        spacerItem24 = QtWidgets.QSpacerItem(20, 115, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_22.addItem(spacerItem24, 0, 1, 1, 1)
        spacerItem25 = QtWidgets.QSpacerItem(51, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_22.addItem(spacerItem25, 1, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.tab_12)
        self.label_23.setText("")
        self.label_23.setPixmap(QtGui.QPixmap("img/help/tel/axis1.png"))
        self.label_23.setObjectName("label_23")
        self.gridLayout_22.addWidget(self.label_23, 1, 1, 1, 1)
        spacerItem26 = QtWidgets.QSpacerItem(51, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_22.addItem(spacerItem26, 1, 2, 1, 1)
        spacerItem27 = QtWidgets.QSpacerItem(20, 114, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_22.addItem(spacerItem27, 2, 1, 1, 1)
        self.tabWidget_4.addTab(self.tab_12, "")
        self.tab_13 = QtWidgets.QWidget()
        self.tab_13.setObjectName("tab_13")
        self.tabWidget_4.addTab(self.tab_13, "")
        self.tab_14 = QtWidgets.QWidget()
        self.tab_14.setObjectName("tab_14")
        self.tabWidget_4.addTab(self.tab_14, "")
        self.tab_15 = QtWidgets.QWidget()
        self.tab_15.setObjectName("tab_15")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.tab_15)
        self.gridLayout_25.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_25.setObjectName("gridLayout_25")
        spacerItem28 = QtWidgets.QSpacerItem(250, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_25.addItem(spacerItem28, 0, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.tab_15)
        self.label_27.setText("")
        self.label_27.setPixmap(QtGui.QPixmap("img/help/qua/quasar_.png"))
        self.label_27.setObjectName("label_27")
        self.gridLayout_25.addWidget(self.label_27, 0, 1, 1, 1)
        spacerItem29 = QtWidgets.QSpacerItem(249, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_25.addItem(spacerItem29, 0, 2, 1, 1)
        self.plainTextEdit_7 = QtWidgets.QPlainTextEdit(self.tab_15)
        self.plainTextEdit_7.setEnabled(False)
        self.plainTextEdit_7.setObjectName("plainTextEdit_7")
        self.gridLayout_25.addWidget(self.plainTextEdit_7, 1, 0, 1, 3)
        self.tabWidget_4.addTab(self.tab_15, "")
        self.tab_16 = QtWidgets.QWidget()
        self.tab_16.setObjectName("tab_16")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.tab_16)
        self.gridLayout_23.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_23.setObjectName("gridLayout_23")
        spacerItem30 = QtWidgets.QSpacerItem(21, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_23.addItem(spacerItem30, 0, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.tab_16)
        self.label_25.setText("")
        self.label_25.setPixmap(QtGui.QPixmap("img/help/tel/sync_.PNG"))
        self.label_25.setObjectName("label_25")
        self.gridLayout_23.addWidget(self.label_25, 0, 1, 2, 1)
        spacerItem31 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_23.addItem(spacerItem31, 1, 2, 1, 1)
        self.plainTextEdit_5 = QtWidgets.QPlainTextEdit(self.tab_16)
        self.plainTextEdit_5.setEnabled(False)
        self.plainTextEdit_5.setObjectName("plainTextEdit_5")
        self.gridLayout_23.addWidget(self.plainTextEdit_5, 2, 0, 1, 2)
        self.tabWidget_4.addTab(self.tab_16, "")
        self.tab_17 = QtWidgets.QWidget()
        self.tab_17.setObjectName("tab_17")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.tab_17)
        self.gridLayout_24.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_24.setObjectName("gridLayout_24")
        spacerItem32 = QtWidgets.QSpacerItem(146, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_24.addItem(spacerItem32, 0, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.tab_17)
        self.label_26.setText("")
        self.label_26.setPixmap(QtGui.QPixmap("img/help/tel/takip_.png"))
        self.label_26.setObjectName("label_26")
        self.gridLayout_24.addWidget(self.label_26, 0, 1, 1, 1)
        spacerItem33 = QtWidgets.QSpacerItem(145, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_24.addItem(spacerItem33, 0, 2, 1, 1)
        self.plainTextEdit_6 = QtWidgets.QPlainTextEdit(self.tab_17)
        self.plainTextEdit_6.setEnabled(False)
        self.plainTextEdit_6.setObjectName("plainTextEdit_6")
        self.gridLayout_24.addWidget(self.plainTextEdit_6, 1, 0, 1, 3)
        self.tabWidget_4.addTab(self.tab_17, "")
        self.gridLayout_18.addWidget(self.tabWidget_4, 0, 0, 1, 1)
        self.tabWidget_3.addTab(self.tab_9, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.tab_10)
        self.gridLayout_19.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.tabWidget_5 = QtWidgets.QTabWidget(self.tab_10)
        self.tabWidget_5.setObjectName("tabWidget_5")
        self.tab_18 = QtWidgets.QWidget()
        self.tab_18.setObjectName("tab_18")
        self.gridLayout_52 = QtWidgets.QGridLayout(self.tab_18)
        self.gridLayout_52.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_52.setObjectName("gridLayout_52")
        spacerItem34 = QtWidgets.QSpacerItem(146, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_52.addItem(spacerItem34, 0, 0, 1, 1)
        self.label_65 = QtWidgets.QLabel(self.tab_18)
        self.label_65.setText("")
        self.label_65.setPixmap(QtGui.QPixmap("img/help/ccd/ccd.jpeg"))
        self.label_65.setObjectName("label_65")
        self.gridLayout_52.addWidget(self.label_65, 0, 1, 1, 1)
        spacerItem35 = QtWidgets.QSpacerItem(145, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_52.addItem(spacerItem35, 0, 2, 1, 1)
        self.plainTextEdit_15 = QtWidgets.QPlainTextEdit(self.tab_18)
        self.plainTextEdit_15.setEnabled(False)
        self.plainTextEdit_15.setObjectName("plainTextEdit_15")
        self.gridLayout_52.addWidget(self.plainTextEdit_15, 1, 0, 1, 3)
        self.tabWidget_5.addTab(self.tab_18, "")
        self.tab_21 = QtWidgets.QWidget()
        self.tab_21.setObjectName("tab_21")
        self.gridLayout_53 = QtWidgets.QGridLayout(self.tab_21)
        self.gridLayout_53.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_53.setObjectName("gridLayout_53")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_21)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 530, 1037))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_54 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_54.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_54.setObjectName("gridLayout_54")
        self.label_66 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_66.setText("")
        self.label_66.setPixmap(QtGui.QPixmap("img/help/ccd/ccd_connec.png"))
        self.label_66.setObjectName("label_66")
        self.gridLayout_54.addWidget(self.label_66, 0, 1, 2, 1)
        self.plainTextEdit_16 = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents)
        self.plainTextEdit_16.setEnabled(False)
        self.plainTextEdit_16.setObjectName("plainTextEdit_16")
        self.gridLayout_54.addWidget(self.plainTextEdit_16, 2, 0, 1, 4)
        spacerItem36 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_54.addItem(spacerItem36, 3, 0, 1, 1)
        spacerItem37 = QtWidgets.QSpacerItem(126, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_54.addItem(spacerItem37, 0, 0, 1, 1)
        spacerItem38 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_54.addItem(spacerItem38, 3, 3, 1, 1)
        self.label_67 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_67.setText("")
        self.label_67.setPixmap(QtGui.QPixmap("img/help/ccd/ccd_nocalib.png"))
        self.label_67.setObjectName("label_67")
        self.gridLayout_54.addWidget(self.label_67, 3, 1, 1, 2)
        spacerItem39 = QtWidgets.QSpacerItem(178, 185, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_54.addItem(spacerItem39, 1, 2, 1, 2)
        self.plainTextEdit_17 = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents)
        self.plainTextEdit_17.setEnabled(False)
        self.plainTextEdit_17.setObjectName("plainTextEdit_17")
        self.gridLayout_54.addWidget(self.plainTextEdit_17, 4, 0, 1, 4)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_53.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.tabWidget_5.addTab(self.tab_21, "")
        self.gridLayout_19.addWidget(self.tabWidget_5, 0, 0, 1, 1)
        self.tabWidget_3.addTab(self.tab_10, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.tab_11)
        self.gridLayout_20.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.tabWidget_6 = QtWidgets.QTabWidget(self.tab_11)
        self.tabWidget_6.setObjectName("tabWidget_6")
        self.tab_20 = QtWidgets.QWidget()
        self.tab_20.setObjectName("tab_20")
        self.tabWidget_6.addTab(self.tab_20, "")
        self.tab_23 = QtWidgets.QWidget()
        self.tab_23.setObjectName("tab_23")
        self.tabWidget_6.addTab(self.tab_23, "")
        self.gridLayout_20.addWidget(self.tabWidget_6, 0, 0, 1, 1)
        self.tabWidget_3.addTab(self.tab_11, "")
        self.tab_24 = QtWidgets.QWidget()
        self.tab_24.setObjectName("tab_24")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.tab_24)
        self.gridLayout_21.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.tabWidget_7 = QtWidgets.QTabWidget(self.tab_24)
        self.tabWidget_7.setObjectName("tabWidget_7")
        self.tab_25 = QtWidgets.QWidget()
        self.tab_25.setObjectName("tab_25")
        self.tabWidget_7.addTab(self.tab_25, "")
        self.tab_26 = QtWidgets.QWidget()
        self.tab_26.setObjectName("tab_26")
        self.tabWidget_7.addTab(self.tab_26, "")
        self.tab_27 = QtWidgets.QWidget()
        self.tab_27.setObjectName("tab_27")
        self.tabWidget_7.addTab(self.tab_27, "")
        self.gridLayout_21.addWidget(self.tabWidget_7, 0, 0, 1, 1)
        self.tabWidget_3.addTab(self.tab_24, "")
        self.gridLayout_16.addWidget(self.tabWidget_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget_8.setCurrentIndex(0)
        self.tabWidget_9.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        self.tabWidget_4.setCurrentIndex(0)
        self.tabWidget_5.setCurrentIndex(0)
        self.tabWidget_6.setCurrentIndex(0)
        self.tabWidget_7.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "ATA50 Gözlem Defteri"))
        self.label_2.setText(_translate("Form", "Hoşgeldiniz"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "ATA50"))
        self.label_24.setText(_translate("Form", "Gözlemciler"))
        self.groupBox_2.setTitle(_translate("Form", "Kayıt"))
        self.label_14.setText(_translate("Form", "ID"))
        self.label_3.setText(_translate("Form", "Tarih"))
        self.pushButton_2.setText(_translate("Form", "Şimdi"))
        self.label_4.setText(_translate("Form", "Dosya Türü"))
        self.comboBox.setItemText(0, _translate("Form", "Obje"))
        self.comboBox.setItemText(1, _translate("Form", "Bias"))
        self.comboBox.setItemText(2, _translate("Form", "Dark"))
        self.comboBox.setItemText(3, _translate("Form", "Flat"))
        self.label_5.setText(_translate("Form", "Poz Süresi"))
        self.label_6.setText(_translate("Form", "Filtre"))
        self.comboBox_2.setItemText(0, _translate("Form", "Johnson(B)"))
        self.comboBox_2.setItemText(1, _translate("Form", "Johnson(V)"))
        self.comboBox_2.setItemText(2, _translate("Form", "Johnson(R)"))
        self.comboBox_2.setItemText(3, _translate("Form", "SDSS(u)"))
        self.comboBox_2.setItemText(4, _translate("Form", "SDSS(g)"))
        self.comboBox_2.setItemText(5, _translate("Form", "SDSS(r)"))
        self.comboBox_2.setItemText(6, _translate("Form", "SDSS(i)"))
        self.comboBox_2.setItemText(7, _translate("Form", "SDSS(z)"))
        self.label_9.setText(_translate("Form", "Obje Adı"))
        self.pushButton_3.setText(_translate("Form", "Bilgi al"))
        self.label_10.setText(_translate("Form", "Sağ Açıklık"))
        self.label_11.setText(_translate("Form", "Dik Açıklık"))
        self.label_20.setText(_translate("Form", "B Mag"))
        self.label_21.setText(_translate("Form", "V Mag"))
        self.label_22.setText(_translate("Form", "R Mag"))
        self.label_68.setText(_translate("Form", "Hava Durumu"))
        self.comboBox_19.setItemText(0, _translate("Form", "1 (Çok Kötü)"))
        self.comboBox_19.setItemText(1, _translate("Form", "2"))
        self.comboBox_19.setItemText(2, _translate("Form", "3"))
        self.comboBox_19.setItemText(3, _translate("Form", "4"))
        self.comboBox_19.setItemText(4, _translate("Form", "5 (Çok iyi)"))
        self.label_8.setText(_translate("Form", "Açıklama"))
        self.pushButton_4.setText(_translate("Form", "Ekle/Düzenle"))
        self.pushButton.setText(_translate("Form", "Çıkar"))
        self.groupBox.setTitle(_translate("Form", "Günün Kayıtları"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("Form", "Gözlem"))
        self.label_19.setText(_translate("Form", "Açıklama"))
        self.label_38.setText(_translate("Form", "Tarih"))
        self.pushButton_7.setText(_translate("Form", "Şimdi"))
        self.label_15.setText(_translate("Form", "Tipi"))
        self.label_16.setText(_translate("Form", "Bölge"))
        self.label_17.setText(_translate("Form", "Cihaz"))
        self.label_18.setText(_translate("Form", "Sorun"))
        self.groupBox_3.setTitle(_translate("Form", "Geri Bildirim Listesi"))
        self.groupBox_4.setTitle(_translate("Form", "Öneri"))
        self.pushButton_5.setText(_translate("Form", "Çıkar"))
        self.pushButton_6.setText(_translate("Form", "Ekle/Düzenle"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("Form", "Sorun Bildir"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), _translate("Form", "Teknik Zaman"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Kayıt Oluştur"))
        self.groupBox_5.setTitle(_translate("Form", "Kayıtlar"))
        self.label_28.setText(_translate("Form", "Gün"))
        self.label_29.setText(_translate("Form", "İçerik"))
        self.groupBox_6.setTitle(_translate("Form", "Kayıt"))
        self.label_30.setText(_translate("Form", "ID"))
        self.label_31.setText(_translate("Form", "Tarih"))
        self.label_33.setText(_translate("Form", "Dosya Türü"))
        self.label_34.setText(_translate("Form", "Poz Süresi"))
        self.label_35.setText(_translate("Form", "Filtre"))
        self.label_36.setText(_translate("Form", "Obje Adı"))
        self.label_37.setText(_translate("Form", "Sağ Açıklık"))
        self.label_39.setText(_translate("Form", "Dik Açıklık"))
        self.label_41.setText(_translate("Form", "B Mag"))
        self.label_42.setText(_translate("Form", "V Mag"))
        self.label_43.setText(_translate("Form", "R Mag"))
        self.label_44.setText(_translate("Form", "Açıklama"))
        self.tabWidget_8.setTabText(self.tabWidget_8.indexOf(self.tab_28), _translate("Form", "Gözlem"))
        self.groupBox_7.setTitle(_translate("Form", "Geri Bildirim Listesi"))
        self.label_49.setText(_translate("Form", "Tarih"))
        self.pushButton_8.setText(_translate("Form", "Şimdi"))
        self.label_40.setText(_translate("Form", "Tipi"))
        self.comboBox_7.setItemText(0, _translate("Form", "Teknik"))
        self.comboBox_7.setItemText(1, _translate("Form", "Kullanıcı"))
        self.comboBox_7.setItemText(2, _translate("Form", "Diğer"))
        self.label_45.setText(_translate("Form", "Bölge"))
        self.comboBox_8.setItemText(0, _translate("Form", "Teleskop Binası"))
        self.comboBox_8.setItemText(1, _translate("Form", "Gözlemci Lojmanı"))
        self.comboBox_8.setItemText(2, _translate("Form", "UPS Odası"))
        self.comboBox_8.setItemText(3, _translate("Form", "Diğer"))
        self.label_46.setText(_translate("Form", "Cihaz"))
        self.label_47.setText(_translate("Form", "Sorun"))
        self.groupBox_8.setTitle(_translate("Form", "Öneri"))
        self.label_48.setText(_translate("Form", "Açıklama"))
        self.tabWidget_9.setTabText(self.tabWidget_9.indexOf(self.tab_31), _translate("Form", "Tümü"))
        self.groupBox_10.setTitle(_translate("Form", "Geri Bildirim Listesi"))
        self.label_56.setText(_translate("Form", "Tarih"))
        self.pushButton_9.setText(_translate("Form", "Şimdi"))
        self.label_51.setText(_translate("Form", "Tipi"))
        self.comboBox_11.setItemText(0, _translate("Form", "Teknik"))
        self.comboBox_11.setItemText(1, _translate("Form", "Kullanıcı"))
        self.comboBox_11.setItemText(2, _translate("Form", "Diğer"))
        self.label_52.setText(_translate("Form", "Bölge"))
        self.comboBox_12.setItemText(0, _translate("Form", "Teleskop Binası"))
        self.comboBox_12.setItemText(1, _translate("Form", "Gözlemci Lojmanı"))
        self.comboBox_12.setItemText(2, _translate("Form", "UPS Odası"))
        self.comboBox_12.setItemText(3, _translate("Form", "Diğer"))
        self.label_53.setText(_translate("Form", "Cihaz"))
        self.label_54.setText(_translate("Form", "Sorun"))
        self.groupBox_9.setTitle(_translate("Form", "Öneri"))
        self.label_55.setText(_translate("Form", "Açıklama"))
        self.tabWidget_9.setTabText(self.tabWidget_9.indexOf(self.tab_32), _translate("Form", "Çözülen"))
        self.groupBox_12.setTitle(_translate("Form", "Geri Bildirim Listesi"))
        self.label_63.setText(_translate("Form", "Tarih"))
        self.pushButton_10.setText(_translate("Form", "Şimdi"))
        self.label_58.setText(_translate("Form", "Tipi"))
        self.comboBox_15.setItemText(0, _translate("Form", "Teknik"))
        self.comboBox_15.setItemText(1, _translate("Form", "Kullanıcı"))
        self.comboBox_15.setItemText(2, _translate("Form", "Diğer"))
        self.label_59.setText(_translate("Form", "Bölge"))
        self.comboBox_16.setItemText(0, _translate("Form", "Teleskop Binası"))
        self.comboBox_16.setItemText(1, _translate("Form", "Gözlemci Lojmanı"))
        self.comboBox_16.setItemText(2, _translate("Form", "UPS Odası"))
        self.comboBox_16.setItemText(3, _translate("Form", "Diğer"))
        self.label_60.setText(_translate("Form", "Cihaz"))
        self.label_61.setText(_translate("Form", "Sorun"))
        self.groupBox_11.setTitle(_translate("Form", "Öneri"))
        self.label_62.setText(_translate("Form", "Açıklama"))
        self.tabWidget_9.setTabText(self.tabWidget_9.indexOf(self.tab_33), _translate("Form", "Bekleyen"))
        self.tabWidget_8.setTabText(self.tabWidget_8.indexOf(self.tab_29), _translate("Form", "Sorun"))
        self.tabWidget_8.setTabText(self.tabWidget_8.indexOf(self.tab_30), _translate("Form", "Teknik Zaman"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "Kayıtları Kontrol Et"))
        self.plainTextEdit_4.setPlainText(_translate("Form", "Mohammad SHAMEONI NIAEI:\n"
"    Tel: 0532 166 1086\n"
"    Email: m.shemuni@gmail.com\n"
"Cihan Tuğrul TEZCAN:\n"
"    Tel: 0543 861 2852\n"
"    Email: 0543 861 2852\n"
"Onur ŞATIR:\n"
"    Tel: 0506 704 6867\n"
"    Email: onur.satir@gmail.com "))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_8), _translate("Form", "İletişim"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_12), _translate("Form", "Axis 1"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_13), _translate("Form", "Enerji"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_14), _translate("Form", "Autoslew"))
        self.plainTextEdit_7.setPlainText(_translate("Form", "Sağ alt tarafta \"Disconnect\" butonu varsa aynaya başarlı biçimde bağlanmışsınız demektir."))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_15), _translate("Form", "Quasar Scope Control"))
        self.plainTextEdit_5.setPlainText(_translate("Form", "Select Object menüsü açılır.\n"
"Teleskobun bulunduğundan emin olduğunuz koordinatı sol üstteki RA ve DE alanlarına yazdıktan sonra sağ alt tarafta kalan \"Synch\" butonuna tklayınız."))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_16), _translate("Form", "Senkronizasyon"))
        self.plainTextEdit_6.setPlainText(_translate("Form", "Görüntü üzerinde 1 numara ile gösterilen yıldız simgesi işaretlenmişse teleskop yıldız takiibi yapmaktadır. Eğer Yer işaretlenmişse takip kapalı demektir.\n"
"Gözlem esnasında telesko daha önce park edildiyse her yönlendirmeden sonra takibi kontrol etmeniz tavsiye edilir."))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_17), _translate("Form", "Takip"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_9), _translate("Form", "Teleskop"))
        self.plainTextEdit_15.setPlainText(_translate("Form", "CCD Enerji ve Veri kablosu şekilde gösterilmiştir.\n"
"CCD bağlantıya hazır olduğunda iki LED ışığı yanıp söner."))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_18), _translate("Form", "Enerji/Veri"))
        self.plainTextEdit_16.setPlainText(_translate("Form", "CCD bağlantı penceresinde \"Connect\" butonuna taıklanmalı."))
        self.plainTextEdit_17.setPlainText(_translate("Form", "Option menüsünde \"No Calibration\" seçeneği işaretlenmiş olmalı."))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_21), _translate("Form", "Maxim DL"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_10), _translate("Form", "CCD"))
        self.tabWidget_6.setTabText(self.tabWidget_6.indexOf(self.tab_20), _translate("Form", "Enerji/Bağlantı"))
        self.tabWidget_6.setTabText(self.tabWidget_6.indexOf(self.tab_23), _translate("Form", "Maxim DL"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_11), _translate("Form", "Filtre Tekeri"))
        self.tabWidget_7.setTabText(self.tabWidget_7.indexOf(self.tab_25), _translate("Form", "Acil Durum Butonu"))
        self.tabWidget_7.setTabText(self.tabWidget_7.indexOf(self.tab_26), _translate("Form", "Açık/Kapalı Kubbe Sensörünün"))
        self.tabWidget_7.setTabText(self.tabWidget_7.indexOf(self.tab_27), _translate("Form", "Kubbe Destekleme"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_24), _translate("Form", "Kubbe"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Form", "Yardım"))

